### ISSUE TITLE
Pointer do not works with lastest version

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-pointer#12]
After updating TTT2 with lastest version this error happend in console(client side)
And the pointer do not show up or show up visually bugged
![image](https://user-images.githubusercontent.com/36534723/104025990-a8f57d80-51c5-11eb-9637-dea9c1553fba.png)

**Comment by ZenBre4ker** [comment]
Can confirm this. Happened to me yesterday too with the latest github version.

**Comment by ZenBre4ker** [comment]
Function IsOffScreen now has to be util.IsOffScreen
https://github.com/TTT-2/TTT2/blob/cb446fd7068f00852e2d789ef4d8e3e570f94e93/lua/ttt2/extensions/util.lua#L471
