### ISSUE TITLE
Spy control (Since he's out of control!)

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/ttt2-pointer#2]
Add a way to stop the spy from being discovered using the pointers.

Possible solutions would be to disable teampointers for traitors if there is a spy in the round.

Or to show the spy pings as normal to traitors, but hide the names on pings from real traitors.

This way the spy can see pings from traitors, and traitors can see the pings of a spy without either being discovered THAT easily. :)

**Comment by Spanospy** [comment]
One thing to keep in mind if pointers are kept while the spy is alive: the spy can use them to bait traitors into revealing themselves.

**Comment by Lunethia** [comment]
Which would be a 42069 IQ move :p

**Comment by TimGoll** [comment]
There is now the hook `TTT2CanUsePointer` that is used by the spy
will be released soon
