### ISSUE TITLE
Unspammify the markers.

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/ttt2-pointer#3]
Either set the limit of markers a player can set to a total of 1.

Or make a convar to regulate the amount.

As is, everyone can spam as many as they want, which, with 6 or more people doing it, is funny, but SLIGHTLY annoying :p

**Comment by TimGoll** [comment]
I thought about this as well
Might do it

**Comment by JayOlino** [comment]
We came to the same conclusion after the first round :D
