### ISSUE TITLE
Disable it for yourself

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/ttt2-pointer#4]
Add the possibility to disable it for yourself if you don't want to see any pings at all.

**Comment by TimGoll** [comment]
This is something I'll probably do once the reworked vgui is done

**Comment by TimGoll** [comment]
implemented in https://github.com/TTT-2/ttt2-pointer/commit/2974127b0f74fe20b0e606ec39c88715a4948f20

![image](https://user-images.githubusercontent.com/13639408/119975656-67b80b80-bfb6-11eb-98e8-7206db41e25d.png)
