### ISSUE TITLE
Spam pointer

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-pointer#5]
I don't know if it is already possible to do it, in fact if it is so you can close the post, I wanted to propose adding the possibility of putting a delay (a cvar server) between one ping and another so as to avoid users who abuse it and spam it

**Comment by Histalek** [comment]
From my understanding `ttt2_pointer_timeout` is the convar you are looking for :) altough im not sure if its in the workshop version already

**Comment by TimGoll** [comment]
there already is a convar
